# Prerequirement

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# !mkdir /content/drive/MyDrive/ML_Project/BCICIV_1_mat

!unzip /content/drive/MyDrive/ML_Project/BCICIV_1_mat.zip -d /content/drive/MyDrive/ML_Project/BCICIV_1_mat

Archive:  /content/drive/MyDrive/ML_Project/BCICIV_1_mat.zip
  inflating: /content/drive/MyDrive/ML_Project/BCICIV_1_mat/BCICIV_calib_ds1a.mat  
  inflating: /content/drive/MyDrive/ML_Project/BCICIV_1_mat/BCICIV_calib_ds1b.mat  
  inflating: /content/drive/MyDrive/ML_Project/BCICIV_1_mat/BCICIV_calib_ds1c.mat  
  inflating: /content/drive/MyDrive/ML_Project/BCICIV_1_mat/BCICIV_calib_ds1d.mat  
  inflating: /content/drive/MyDrive/ML_Project/BCICIV_1_mat/BCICIV_calib_ds1e.mat  
  inflating: /content/drive/MyDrive/ML_Project/BCICIV_1_mat/BCICIV_calib_ds1f.mat  
  inflating: /content/drive/MyDrive/ML_Project/BCICIV_1_mat/BCICIV_calib_ds1g.mat  
  inflating: /content/drive/MyDrive/ML_Project/BCICIV_1_mat/BCICIV_eval_ds1a.mat  
  inflating: /content/drive/MyDrive/ML_Project/BCICIV_1_mat/BCICIV_eval_ds1b.mat  
  inflating: /content/drive/MyDrive/ML_Project/BCICIV_1_mat/BCICIV_eval_ds1c.mat  
  inflating: /content/drive/MyDrive/ML_Project/BCICIV_1_mat/BCICIV_eval_ds1d.mat  
  inflating: /conte

In [ ]:
!pip install scipy

import scipy.io
import os

folder_path = '/content/drive/MyDrive/ML_Project/BCICIV_1_mat/'

mat_files = [f for f in os.listdir(folder_path) if f.endswith('.mat')]

def load_and_display_mat_file(file_path):
    mat_contents = scipy.io.loadmat(file_path)
    print(f"Contents of {file_path} : \n")
    for key in mat_contents:
        if not key.startswith('__'):
            print(f"{key}   :  {mat_contents[key]}")
    return mat_contents

for mat_file in mat_files:
    file_path = os.path.join(folder_path, mat_file)
    load_and_display_mat_file(file_path)

In [ ]:
mat1 = load_and_display_mat_file('/content/drive/MyDrive/ML_Project/BCICIV_1_mat/BCICIV_calib_ds1a.mat')

Contents of /content/drive/MyDrive/ML_Project/BCICIV_1_mat/BCICIV_calib_ds1a.mat:
mrk: [[(array([[  2091,   2891,   3691,   4491,   5291,   6091,   6891,   7692,
            8492,   9292,  10092,  10892,  11692,  12492,  13292,  16294,
           17094,  17894,  18694,  19494,  20294,  21094,  21894,  22694,
           23494,  24294,  25094,  25894,  26694,  27494,  30495,  31295,
           32095,  32895,  33695,  34495,  35295,  36095,  36895,  37695,
           38495,  39295,  40095,  40895,  41695,  44696,  45496,  46296,
           47096,  47896,  48696,  49496,  50296,  51096,  51896,  52696,
           53496,  54296,  55096,  55896,  58895,  59695,  60495,  61295,
           62095,  62895,  63695,  64495,  65295,  66095,  66895,  67695,
           68495,  69295,  70095,  73094,  73894,  74694,  75495,  76295,
           77095,  77895,  78695,  79495,  80295,  81095,  81895,  82695,
           83495,  84295,  87294,  88094,  88894,  89694,  90494,  91294,
           92094,  92894

In [ ]:
mat2 = load_and_display_mat_file('/content/drive/MyDrive/ML_Project/BCICIV_1_mat/BCICIV_eval_ds1a.mat')

Contents of /content/drive/MyDrive/ML_Project/BCICIV_1_mat/BCICIV_eval_ds1a.mat:
cnt: [[  -4   -9  -22 ...  -20  -17  -15]
 [ -29  -75 -171 ... -151 -131 -113]
 [ -50 -168 -352 ... -314 -270 -238]
 ...
 [  97 -238    9 ...  -35   33  -24]
 [ 105 -263   42 ... -134  101 -127]
 [  41 -330  -12 ... -326    1 -303]]
nfo: [[(array([[100]], dtype=uint8), array([[array(['left'], dtype='<U4'), array(['foot'], dtype='<U4')]],
        dtype=object), array([[array(['AF3'], dtype='<U3'), array(['AF4'], dtype='<U3'),
          array(['F5'], dtype='<U2'), array(['F3'], dtype='<U2'),
          array(['F1'], dtype='<U2'), array(['Fz'], dtype='<U2'),
          array(['F2'], dtype='<U2'), array(['F4'], dtype='<U2'),
          array(['F6'], dtype='<U2'), array(['FC5'], dtype='<U3'),
          array(['FC3'], dtype='<U3'), array(['FC1'], dtype='<U3'),
          array(['FCz'], dtype='<U3'), array(['FC2'], dtype='<U3'),
          array(['FC4'], dtype='<U3'), array(['FC6'], dtype='<U3'),
          array(['CFC

# PreProcess Data

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# Install necessary libraries
!pip install scipy
!pip install mne
!pip install scikit-learn

In [ ]:
!conda install -c rapidsai -c nvidia -c conda-forge cuml=21.12 python=3.10 cudatoolkit=11.2 --yes

/bin/bash: line 1: conda: command not found


In [ ]:
!pip install cuml
import cuml
from cuml.manifold import TSNE

  Preparing metadata (setup.py) ... done
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cuml
  Running setup.py clean for cuml
Failed to build cuml
ERROR: Could not build wheels for cuml, which is required to install pyproject.toml-based projects


ModuleNotFoundError: No module named 'cuml'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import scipy.io
import scipy.signal as signal
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA, FastICA
from sklearn.manifold import TSNE
from mne.decoding import CSP

# Load the EEG data from .mat file
file_path = '/content/drive/MyDrive/ML_Project/BCICIV_1_mat/BCICIV_calib_ds1a.mat'
data = scipy.io.loadmat(file_path)

# Extract relevant data
eeg_signals = data['cnt']
eeg_markers = data['mrk']
eeg_info = data['nfo']

# 1. Low-pass Filter
def low_pass_filter(data, cutoff=40, fs=250, order=5):
    nyquist = 0.5 * fs
    normal_cutoff = cutoff / nyquist
    b, a = signal.butter(order, normal_cutoff, btype='low', analog=False)
    filtered_data = signal.filtfilt(b, a, data, axis=0)
    return filtered_data

filtered_signals = low_pass_filter(eeg_signals)

# 2. Spatial Filtering

# Common Average Reference (CAR) Filtering
def car_filter(data):
    car_signal = data - np.mean(data, axis=1, keepdims=True)
    return car_signal

car_signals = car_filter(filtered_signals)

# Laplacian Filtering (simplified example)
def laplacian_filter(data):
    laplacian_signal = data - np.mean(data, axis=1, keepdims=True)
    return laplacian_signal

laplacian_signals = laplacian_filter(filtered_signals)

# PCA
pca = PCA(n_components=10)
pca_signals = pca.fit_transform(filtered_signals)

# ICA
ica = FastICA(n_components=10)
ica_signals = ica.fit_transform(filtered_signals)

# 3. t-SNE for Signal Visualization
def plot_tsne(data, labels, title):
    tsne = TSNE(n_components=2, random_state=42)
    tsne_result = tsne.fit_transform(data)
    plt.figure(figsize=(10, 6))
    plt.scatter(tsne_result[:, 0], tsne_result[:, 1], c=labels, cmap='viridis', s=2)
    plt.colorbar()
    plt.title(title)
    plt.show()

# Reduce dimensions before t-SNE
pca_for_tsne = PCA(n_components=50)
reduced_signals = pca_for_tsne.fit_transform(filtered_signals)

# Correctly accessing the labels
labels = eeg_markers[0][0][1].flatten()
# plot_tsne(reduced_signals, labels, "t-SNE Visualization of Filtered EEG Signals")

# 4. Feature Extraction with CSP (Common Spatial Patterns)
csp = CSP(n_components=4, reg=None, log=True, norm_trace=False)
labels = np.where(labels == -1, 0, labels)
csp_features = csp.fit_transform(filtered_signals, labels)

# Visualize CSP features
# plot_tsne(csp_features, labels, "t-SNE Visualization of CSP Features")

print("Preprocessing complete.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


/usr/local/lib/python3.10/dist-packages/sklearn/decomposition/_fastica.py:542: FutureWarning: Starting in v1.3, whiten='unit-variance' will be used by default.
  warnings.warn(


ValueError: X and y must have the same length.

# Classification

In [ ]:
import scipy.io
import scipy.signal as signal
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA, FastICA
from sklearn.manifold import TSNE
from mne.decoding import CSP
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

file_path = '/content/drive/MyDrive/ML_Project/BCICIV_1_mat/BCICIV_calib_ds1a.mat'
data = scipy.io.loadmat(file_path)

eeg_signals = data['cnt']
eeg_markers = data['mrk']
eeg_info = data['nfo']

# 1. Low-pass Filter
def low_pass_filter(data, cutoff=40, fs=250, order=5):
    nyquist = 0.5 * fs
    normal_cutoff = cutoff / nyquist
    b, a = signal.butter(order, normal_cutoff, btype='low', analog=False)
    filtered_data = signal.filtfilt(b, a, data, axis=0)
    return filtered_data

filtered_signals = low_pass_filter(eeg_signals)

# 2. Spatial Filtering

# Common Average Reference (CAR) Filtering
def car_filter(data):
    car_signal = data - np.mean(data, axis=1, keepdims=True)
    return car_signal

car_signals = car_filter(filtered_signals)

# Laplacian Filtering (simplified example)
def laplacian_filter(data):
    laplacian_signal = data - np.mean(data, axis=1, keepdims=True)
    return laplacian_signal

laplacian_signals = laplacian_filter(filtered_signals)

# PCA
pca = PCA(n_components=10)
pca_signals = pca.fit_transform(filtered_signals)

# ICA
ica = FastICA(n_components=10)
ica_signals = ica.fit_transform(filtered_signals)

# 3. t-SNE for Signal Visualization
def plot_tsne(data, labels, title):
    tsne = TSNE(n_components=2, random_state=42)
    tsne_result = tsne.fit_transform(data)
    plt.figure(figsize=(10, 6))
    plt.scatter(tsne_result[:, 0], tsne_result[:, 1], c=labels, cmap='viridis', s=2)
    plt.colorbar()
    plt.title(title)
    plt.show()

# Reduce dimensions before t-SNE
pca_for_tsne = PCA(n_components=50)
reduced_signals = pca_for_tsne.fit_transform(filtered_signals)

# Correctly accessing the labels
labels = eeg_markers[0][0][1].flatten()
# plot_tsne(reduced_signals, labels, "t-SNE Visualization of Filtered EEG Signals")

# 4. Feature Extraction with CSP (Common Spatial Patterns)
csp = CSP(n_components=4, reg=None, log=True, norm_trace=False)
labels = np.where(labels == -1, 0, labels)
csp_features = csp.fit_transform(filtered_signals, labels)

# Visualize CSP features
# plot_tsne(csp_features, labels, "t-SNE Visualization of CSP Features")

# 5. Classification
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(csp_features, labels, test_size=0.3, random_state=42)

# Logistic Regression
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr_pred = lr.predict(X_test)
lr_acc = accuracy_score(y_test, lr_pred)
print("Logistic Regression Accuracy:", lr_acc)
print(classification_report(y_test, lr_pred))

# Support Vector Machine
svm = SVC()
svm.fit(X_train, y_train)
svm_pred = svm.predict(X_test)
svm_acc = accuracy_score(y_test, svm_pred)
print("SVM Accuracy:", svm_acc)
print(classification_report(y_test, svm_pred))

# Random Forest
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)
rf_acc = accuracy_score(y_test, rf_pred)
print("Random Forest Accuracy:", rf_acc)
print(classification_report(y_test, rf_pred))

# K-Nearest Neighbors
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
knn_pred = knn.predict(X_test)
knn_acc = accuracy_score(y_test, knn_pred)
print("KNN Accuracy:", knn_acc)
print(classification_report(y_test, knn_pred))

print("Classification complete.")


/usr/local/lib/python3.10/dist-packages/sklearn/decomposition/_fastica.py:542: FutureWarning: Starting in v1.3, whiten='unit-variance' will be used by default.
  warnings.warn(
